name: Deploy backend to Fly.io

on:
  push:
    branches: [master]
    paths:
      - "backend/**"
      - ".github/workflows/fly-deploy-backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-backend-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_BACKEND }}
